### ISSUE TITLE
Use autoupdating npm shields instead of static text for version numbers

### ISSUE THREAD

**Issue by buildbreakdo** [MicheleBertoli/css-in-js#37]
In the version column if we had these:

[<img title="Version" src="https://img.shields.io/npm/v/style-it.svg?style=flat-square" />](https://www.npmjs.org/package/style-it)

Instead of static text, it would decrease the burden to update and also be a more accurate living reflection of what version these packages are on. Cheers

**Comment by MicheleBertoli** [comment]
hey @buildbreakdo 

I understand your point but the purpose of the version number column is not to show the current version number.
The number in the column should reflect the version of the package at the time it has been used to create the example with the features of that particular version.

Otherwise, the relation version / features would be wrong.

I hope it makes sense for you, I'm going to close the issue.
